.gitignore, .gitmodules, build.gradle, src/main/java/com/moonbaar/common/entity/BaseEntity.java, src/main/java/com/moonbaar/common/entity/BaseEntityWithUpdate.java, src/main/java/com/moonbaar/common/exception/BusinessException.java, src/main/java/com/moonbaar/common/exception/ErrorCode.java, src/main/java/com/moonbaar/common/exception/ErrorResponse.java, src/main/java/com/moonbaar/common/exception/GlobalErrorCode.java, src/main/java/com/moonbaar/common/exception/GlobalExceptionHandler.java, src/main/java/com/moonbaar/common/utils/JsonUtils.java, src/main/resources/application.properties
close #2 
기본 프로젝트 구조를 설정했습니다.
- BaseEntity 구현
- BusinessException 구현
- GlobalExceptionHandler 구현
- ErrorResponse 클래스 구현
- 기본 에러 코드 정의
- 데이터 유효성 검증을 위한 spring-boot-starter-validation 의존성 추가
- 설정 파일을 보안을 위해 Git submodule로 분리 (private repository)
- application*.properties → `src/main/resources/config`로 이동
- `config` 디렉토리는 Git submodule로 연동
- 민감한 설정은 `.gitignore`에 등록하여 커밋 제외 처리
=> chore: 프로젝트 기본 구조 설정

src/main/java/com/moonbaar/common/config/SecurityConfig.java, src/main/java/com/moonbaar/domain/category/entity/Category.java, src/main/java/com/moonbaar/domain/district/entity/District.java, src/main/java/com/moonbaar/domain/event/controller/EventController.java, src/main/java/com/moonbaar/domain/event/dto/EventListResponse.java, src/main/java/com/moonbaar/domain/event/dto/EventSearchRequest.java, src/main/java/com/moonbaar/domain/event/dto/EventSummaryResponse.java, src/main/java/com/moonbaar/domain/event/entity/CulturalEvent.java, src/main/java/com/moonbaar/domain/event/exeption/EventErrorCode.java, src/main/java/com/moonbaar/domain/event/repository/CulturalEventRepository.java, src/main/java/com/moonbaar/domain/event/repository/EventSpecifications.java, src/main/java/com/moonbaar/domain/event/service/EventService.java, src/test/java/com/moonbaar/domain/event/repository/CulturalEventRepositoryTest.java
- #4 
> 서울시 공공데이터 API를 활용한 문화행사 정보를 검색하고 조회할 수 있는 API를 구현했습니다. 현재 user 관련 코드가 구현되지 않아 유저 정보가 필요한 목록은 빼고 응답을 하도록 구현했습니다.
1. **문화행사 관련 엔티티 구현**
- `CulturalEvent`, `Category`, `District` 엔티티 구현
- 파이썬 스크립트로 생성된 DB 스키마와 일치하도록 `BaseEntity` 상속 제거
2. **JPA Specification을 활용한 동적 검색 쿼리 구현**
- 다양한 검색 조건(키워드, 카테고리, 지역, 날짜, 무료/유료)에 따른 동적 쿼리 생성
- 각 검색 조건별 Predicate 생성 메서드 분리
3. **문화행사 목록 조회 API 개발**
- `GET /events` 엔드포인트 구현
- 페이징, 정렬 기능 구현
- Spring Security 설정으로 인증 없이 접근 가능하도록 설정
4. **DTO, 서비스, 컨트롤러 구현**
이번 구현을 통해 JPA Specification 패턴에 대해 공부할 수 있었습니다.
원래는 복잡한 쿼리를 작성할 때 JPQL을 직접 사용하는 방법만 알고 있었습니다. 그러나 검색어, 카테고리, 지역, 날짜, 무료/유료 등 다양한 검색 조건이 선택적으로 적용되는 동적 쿼리의 경우, JPQL 사용이 복잡하고 오류 가능성이 높아 JPA Specification 이나 QueryDSL 패턴을 사용한다는 것을 알게됐습니다.
따라서 JPA Specification 패턴을 적용하여 조회 로직을 구현했습니다.
JPA Specification은 …
=> feat: 행사 목록 조회 api 구현

.github/workflows/deploy.yml, src/main/java/com/moonbaar/domain/event/controller/EventController.java, src/main/java/com/moonbaar/domain/event/dto/EventDetailResponse.java, src/main/java/com/moonbaar/domain/event/dto/EventSummaryResponse.java, src/main/java/com/moonbaar/domain/event/exeption/EventNotFoundException.java, src/main/java/com/moonbaar/domain/event/service/EventService.java, src/test/java/com/moonbaar/common/config/SecurityTestConfig.java, src/test/java/com/moonbaar/domain/event/controller/EventControllerTest.java, src/test/java/com/moonbaar/domain/event/service/EventServiceTest.java
- #10 
서울시 문화행사 데이터를 기반으로 특정 행사의 상세 정보를 조회할 수 있는 API를 구현했습니다. 사용자가 문화 행사에 대한 자세한 정보를 확인할 수 있는 기능입니다.
- 행사 상세 정보 응답 DTO(EventDetailResponse) 생성
- 행사 상세 정보 조회 서비스 로직 구현
- 행사 상세 정보 조회 컨트롤러 엔드포인트 구현
- 서비스 및 컨트롤러에 대한 단위 테스트 추가
- 엔드포인트: `GET /api/events/{eventId}`
- 응답 형식: 행사 상세 정보를 포함한 JSON 객체
- 오류 코드: 404 (행사 정보 없음)
사용자 관련 기능(좋아요, 방문 인증 등)은 사용자 모듈 구현 후 추후 확장 예정입니다.
=> feat: 행사 상세 조회 api 구현

.github/workflows/deploy.yml, src/main/java/com/moonbaar/domain/category/controller/CategoryController.java, src/main/java/com/moonbaar/domain/category/dto/CategoryListResponse.java, src/main/java/com/moonbaar/domain/category/dto/CategoryResponse.java, src/main/java/com/moonbaar/domain/category/exception/CategoryErrorCode.java, src/main/java/com/moonbaar/domain/category/exception/CategoryNotFoundException.java, src/main/java/com/moonbaar/domain/category/repository/CategoryRepository.java, src/main/java/com/moonbaar/domain/category/service/CategoryService.java, src/main/java/com/moonbaar/domain/district/controller/DistrictController.java, src/main/java/com/moonbaar/domain/district/dto/DistrictListResponse.java, src/main/java/com/moonbaar/domain/district/dto/DistrictResponse.java, src/main/java/com/moonbaar/domain/district/exception/DistrictErrorCode.java, src/main/java/com/moonbaar/domain/district/exception/DistrictNotFoundException.java, src/main/java/com/moonbaar/domain/district/repository/DistrictRepository.java, src/main/java/com/moonbaar/domain/district/service/DistrictService.java, src/test/java/com/moonbaar/domain/category/controller/CategoryControllerTest.java, src/test/java/com/moonbaar/domain/district/controller/DistrictControllerTest.java
- #14 
문화발자국 서비스에서 필요한 카테고리와 행정구역 정보를 조회할 수 있는 API를 구현했습니다.
카테고리와 행정구역의 ID를 반환하고 해당 ID를 통해 프론트엔드에서 행사목록 필터링을 할 수 있도록 했습니다.
- 카테고리/행정구역 목록 조회 API 구현 (GET /categories, GET /districts)
- 이름으로 단일 카테고리/행정구역 조회 API 구현 (GET /categories/by-name/{name}, GET /districts/by-name/{name})
- 정적 팩토리 메서드 패턴을 적용한 DTO 구현
- Repository, Service, Controller 계층 구현
- Given-When-Then 패턴을 적용한 단위 테스트 작성
- 전체 목록 조회
- 엔드포인트: GET /api/categories, GET /api/districts
- 응답 형식: 카테고리/행정구역 목록을 포함한 JSON 객체
- 이름으로 단일 조회
- 엔드포인트: GET /api/categories/by-name/{name}, GET /api/districts/by-name/{name}
- 응답 형식: 단일 카테고리/행정구역 정보를 포함한 JSON 객체
- 오류 코드: 404 (해당 이름의 카테고리/행정구역이 없음)
```json
// GET /api/categories
{
"categories": [
{ "id": 1, "name": "연극" },
{ "id": 2, "name": "전시/미술" },
{ "id": 3, "name": "콘서트" }
]
}
// GET …
```
=> feat: 카테고리, 행정구역 목록 조회 api 구현 

docker-files/data-init/get_cultural_events.py
- #19 
행정구역과 카테고리 ID를 지정된 값으로 초기화 하도록 데이터 초기화 컨테이너의 파이썬 스크립트를 수정했습니다.
category와 district의 id를 지정된 값으로 고정했습니다.
```
1	교육/체험
2	국악
3	독주/독창회
4	뮤지컬/오페라
5	무용
6	연극
7	영화
8	전시/미술
9	축제-기타
10	축제-문화/예술
11	축제-시민화합
12	축제-자연/경관
13	축제-전통/역사
14	클래식
15	콘서트
16	기타
```
```
1	강남구
2	강동구
3	강북구
4	강서구
5	관악구
6	광진구
7	구로구
8	금천구
9	노원구
10	도봉구
11	동대문구
12	동작구
13	마포구
14	서대문구
15	서초구
16	성동구
17	성북구
18	송파구
19	양천구
20	영등포구
21	용산구
22	은평구
23	종로구
24	중구
25	중랑구
26	기타
```
=> refactor: 행정구역과 카테고리 ID를 지정된 값으로 고정

src/main/java/com/moonbaar/domain/event/repository/EventSpecifications.java, src/test/java/com/moonbaar/domain/event/repository/CulturalEventRepositoryTest.java
- #25 
- EventSpecifications 클래스의 addDatePredicates 메서드 로직 수정
- 단위 테스트 추가
- 기존: 특정 기간에 '시작하는' 행사만 검색했었습니다.
```
ex) startDate=2025-04-15로 검색했을 때 3월부터 시작하여 진행 중인 행사가 있었다면 검색 안 됨.
```
- 개선: 특정 기간 동안 '진행 중인' 행사를 검색하도록 하였습니다.
```
ex) startDate=2025-04-15로 검색했을 때 3월부터 시작하여 진행 중인 행사도 검색이 됨.
```
- 검색 조건: (행사 종료일 >= 검색 시작일) AND (행사 시작일 <= 검색 종료일)
=> refactor: 행사 검색 시 날짜 필터링 로직 개선

src/main/java/com/moonbaar/MoonbaarApplication.java, src/main/java/com/moonbaar/domain/like/controller/LikeController.java, src/main/java/com/moonbaar/domain/like/dto/LikeResponse.java, src/main/java/com/moonbaar/domain/like/entity/LikedEvent.java, src/main/java/com/moonbaar/domain/like/exception/AlreadyLikedEventException.java, src/main/java/com/moonbaar/domain/like/exception/LikeErrorCode.java, src/main/java/com/moonbaar/domain/like/exception/LikeNotFoundException.java, src/main/java/com/moonbaar/domain/like/repository/LikedEventRepository.java, src/main/java/com/moonbaar/domain/like/service/LikeService.java, src/main/java/com/moonbaar/domain/user/entity/User.java, src/main/java/com/moonbaar/domain/user/exception/UserErrorCode.java, src/main/java/com/moonbaar/domain/user/exception/UserNotFoundException.java, src/main/java/com/moonbaar/domain/user/repository/UserRepository.java, src/test/java/com/moonbaar/domain/like/controller/LikeControllerTest.java
- #22 
- 좋아요 엔티티(`LikedEvent`) 및 제약조건 구현
- 좋아요 서비스 및 컨트롤러 구현
- 관련 예외 처리 및 응답 DTO 구현
- 이벤트 상세 조회 시 좋아요 상태 포함
- 단위 테스트 작성 
- 테스트용 Mock 사용자 데이터 SQL 구현
- JPA Auditing 설정 추가 (`@EnableJpaAuditing`)
사용자가 행사에 좋아요를 표시할 수 있는 API를 구현했습니다. (`POST /events/{eventId}/like`)
좋아요 취소 API를 구현했습니다. (`DELETE /events/{eventId}/like`)
이에 따라 이벤트 상세 정보 조회 시 기존에는 false로 고정하여 돌려주었던 좋아요 여부를 실제 db에서 조회해 응답합니다.
중복 좋아요 방지를 위한 제약 조건 및 예외 처리를 구현했습니다.
현재 OAuth 인증 없이 목 사용자(ID: 1)로 사용자가 고정되게 해두었습니다. 현재 리퀘스트의 결과는 ID 1 유저의 좋아요 정보로 들어가게 됩니다.
좋아요 기능 구현 중 `@EnableJpaAuditing` 어노테이션 누락으로 인해 BaseEntity의 createdAt 필드가 null로 저장되는 문제가 발생했으나, 애플리케이션 클래스에 해당 어노테이션을 추가하여 해결했습니다.
=> feat: 행사 좋아요 API 구현

.github/workflows/deploy.yml, build.gradle, src/main/java/com/moonbaar/common/config/SecurityConfig.java, src/main/java/com/moonbaar/common/dto/OAuthAttributes.java, src/main/java/com/moonbaar/common/filter/JwtAuthenticationFilter.java, src/main/java/com/moonbaar/common/oauth/CustomOAuth2User.java, src/main/java/com/moonbaar/common/oauth/TokenBlackList.java, src/main/java/com/moonbaar/common/oauth/dto/OAuthAttributes.java, src/main/java/com/moonbaar/common/oauth/handler/OAuth2SuccessHandler.java, src/main/java/com/moonbaar/common/oauth/service/CustomOAuth2UserService.java, src/main/java/com/moonbaar/common/service/CustomOAuth2UserService.java, src/main/java/com/moonbaar/common/utils/JwtUtils.java, src/main/java/com/moonbaar/domain/user/controller/UserController.java, src/main/java/com/moonbaar/domain/user/entity/User.java, src/main/java/com/moonbaar/domain/user/exception/UserAccessDeniedException.java, src/main/java/com/moonbaar/domain/user/exception/UserErrorCode.java, src/main/java/com/moonbaar/domain/user/repository/UserRepository.java, src/main/java/com/moonbaar/domain/user/service/UserService.java
- #6 
> OAuth2 소셜 로그인 기능을 구현하고 JWT 기반 인증 처리 구현
1. **네이버/카카오 OAuth2 로그인 구현**
- `SecurityConfig` 설정
- `CustomOAuth2UserService`로 사용자 정보를 가져오고, `OAuthAttributes`을 이용해 사용자 정보를 같은 형태로 관리
- `OAuth2SuccessHandler`에서 토큰 관련 처리 후 `/login-success`로 리다이렉트
2. **JWT 기반 인증 처리**
- `JwtUtils`에서 Access Token/Refresh Token 을 생성 및 관리
- Access Token이 만료 되었을 때 Refresh Token으로 재발급 가능하도록 `POST/users/refresh` 구현
- Refresh Token을 DB에서 제거하고 Access Token을 `TokenBlackList`에 추가하는 `POST/users/logout` 구현
- JWT를 검증하는 `JwtAuthenticationFilter` 구현
.
- 인증/인가 관련 `/users/logout`, `/users/refresh` 등을 `/auth/logout` 등 `auth`로 변경하거나 필터 제외할 경로를 세분화
- `JwtAuthenticationFilter`에서도 `GlobalExceptionHandler` 처리
- 인메모리로 방식인 `TokenBlackList`를 Redis 등을 사용하여 관리하도록 변경
=> feat: OAuth2 로그인 기능 구현

src/main/java/com/moonbaar/domain/like/dto/LikedEventListResponse.java, src/main/java/com/moonbaar/domain/like/dto/LikedEventResponse.java, src/test/java/com/moonbaar/domain/user/controller/UserControllerTest.java
- 좋아요 목록 조회 응답 필드명을
행사 목록 조회 응답 필드명과 통일되게 변경하였습니다.
``likes`` -> ``events``
``eventId`` -> ``id``
- 불필요한 ``likedAt`` 필드를 제거하였습니다.
```json
{ "totalCount": 15, "totalPages": 1, "currentPage": 1, "events": [ { "id": "이벤트ID", "title": "행사명", "place": "장소명", "startDate": "2025-04-10T10:00:00Z", "endDate": "2025-04-10T18:00:00Z", "mainImg": "이미지URL" }, ... ] }
```
=> refactor: 좋아요 목록 조회 api 응답 필드명 변경

src/main/java/com/moonbaar/domain/visit/controller/FootPrintController.java, src/main/java/com/moonbaar/domain/visit/controller/FootprintController.java, src/main/java/com/moonbaar/domain/visit/dto/FootprintListResponse.java, src/main/java/com/moonbaar/domain/visit/dto/FootprintRequest.java, src/main/java/com/moonbaar/domain/visit/dto/FootprintResponse.java, src/main/java/com/moonbaar/domain/visit/repository/VisitRepository.java, src/main/java/com/moonbaar/domain/visit/service/FootprintService.java, src/test/java/com/moonbaar/domain/visit/controller/FootprintControllerTest.java
- #23 
- 지도에 방문 이력 표시를 위한 `/users/me/footprints` API 구현
- 지도 범위(bounds) 내 방문 장소만 필터링하는 기능 구현
- 필요한 DTO, 서비스, 레포지토리 로직 구현
- 테스트 코드 추가 (컨트롤러, 서비스, 레포지토리)
- `/users/me/footprints` 엔드포인트로 사용자가 방문한 위치를 지도에 표시할 수 있도록 구현했습니다.
- 지도에 보이는 영역(bounds)에 해당하는 방문 기록만 효율적으로 가져오기 위해 위도/경도 범위 기반 쿼리를 작성했습니다.
- 필수 파라미터(minLat, maxLat, minLng, maxLng)를 통해 지도 범위를 지정하도록 했습니다.
Visit 엔티티에 CulturalEvent가 지연 로딩으로 설정되어 있어
방문 목록을 가져오고, 해당하는 이벤트 정보를 반환하는 로직에서 N+1 Query 문제가 발생했었습니다.
```
// Visit 엔티티를 조회하는 쿼리 (1개)
Hibernate: 
select
v1_0.id,
v1_0.created_at,
v1_0.event_id,
v1_0.user_id,
v1_0.visited_at 
from
visits v1_0 
join
cultural_events e1_0 
on e1_0.id=v1_0.event_id 
where
v1_0.user_id=? 
and e1_0.latitude>=? 
and e1_0.latitude<=? 
and e1_0.longitude>=? 
and e1_0.longitude<=?
// 이후 각 Visit에 대해 CulturalEvent를 조회하는 …
```
=> feat: 발자국 지도(지도 범위 기반 방문 위치 조회) api 구현

.github/workflows/deploy.yml, docker-compose.yml, src/main/java/com/moonbaar/domain/like/entity/LikedEvent.java, src/main/java/com/moonbaar/domain/like/repository/LikedEventRepository.java
- #40 
- 좋아요 목록 조회 API에서 발생하던 N+1 쿼리 문제 해결
- 이벤트와 좋아요 간 참조 무결성 보장을 위한 외래 키 제약조건 추가
발자국 지도 API를 구현하며 좋아요 목록 조회 API에서도 N+1 문제가 발생하고 있음을 확인했습니다.
```sql
Hibernate:        -- 1번의 쿼리
select
u1_0.id,
...
from
users u1_0 
where
u1_0.id=?
Hibernate: 
select
le1_0.id,
...
from
liked_events le1_0 
where
le1_0.user_id=? 
order by
le1_0.created_at desc 
limit
?
Hibernate:        -- N번 반복되는 쿼리
select
ce1_0.id,
...
from
cultural_events ce1_0 
where
ce1_0.id=?
Hibernate: 
select
ce1_0.id,
...
from
cultural_events ce1_0 
where
ce1_0.id=?
...
```
이는 `LikedEvent` 엔티티를 조회할 때 LAZY로 페치 타입이 설정된 CulturalEvent를 프록시 객체로 가지고 있다가, 실제로 이벤트 정보가 필요한 시점에 추가적인 쿼리가 발생하기 때문이었습니다. 20개의 좋아요 항목이 있다면 총 21번의 쿼리가 실행되는 상황이었습니다.
보통 N+1 문제를 해결할 때 join fetch를 사용합니다. 그런데 정보를 찾아보던 중 JPA에서 페이징과 fetch join을 함께 사용할 수 없다는 [블로그 …
=> refactor:  JPA N+1 문제 해결 및 참조 무결성 개선

src/main/java/com/moonbaar/common/config/SecurityConfig.java, src/main/java/com/moonbaar/common/filter/JwtAuthenticationFilter.java, src/main/java/com/moonbaar/common/oauth/CustomUserDetails.java, src/main/java/com/moonbaar/common/oauth/service/CustomUserDetailsService.java, src/main/java/com/moonbaar/domain/like/entity/LikedEvent.java, src/main/java/com/moonbaar/domain/user/controller/UserController.java, src/main/java/com/moonbaar/domain/user/dto/UserInfoResponse.java, src/main/java/com/moonbaar/domain/user/repository/UserRepository.java, src/main/java/com/moonbaar/domain/user/service/UserService.java, src/main/java/com/moonbaar/domain/visit/entity/Visit.java
- #42 
> 로그인된 사용자 정보 조회 및 회원 탈퇴 기능 구현
1. `UserDetails`를 `SecurityContext`에 등록하여 `@AuthenticationPrincipal` 으로 로그인된 사용자 정보를 확인할 수 있도록 했습니다.
2. 인증 예외 처리 EntryPoint를 설정하여 JWT 인증 실패시 401로 응답하도록하였습니다.
추후 클래스를 직접 구현하여 `GlobalExceptionHandler`를 사용하도록 변경할 예정입니다.
3. 사용자 정보를 조회하는 `GET /users/me` 엔드포인트를 구현했습니다.
4. 사용자 정보를 삭제하는 `DELETE /users/me` 엔드포인트를 구현했습니다.
회원탈퇴시 사용자의 방문 데이터와 좋아요 데이터를 같이 삭제할 수 있도록 `DELETE CASCADE` 제약조건을 추가하였습니다.
JPA에서 `User`와 `Visit`/`LikedEvent`를 양방향 처리하지 않고 DB 상에서 CASCADE 될 수 있도록 하였습니다.
소셜로그인 인증 철회는 추후 구현할 예정입니다.
1. Kakao의 경우 access token이 필요하여 로그인시 이를 따로 관리하는 로직이 필요합니다.
3. 외부 API이용에 따른 트랜잭션 분리 및 인증 철회 실패시 재시도에 관한 로직을 고려해야합니다.
.
- `AuthenticationEntryPoint` 구현 및  `GlobalExceptionHandler` 적용
- 로그아웃에 사용되는 accessToken/refreshToken 만료 로직을 분리하여 재사용할 수 있도록 함
- kakao 로그인 시 access …
=> feat: 사용자 관련 api 구현

src/main/java/com/moonbaar/domain/badge/controller/BadgeController.java, src/main/java/com/moonbaar/domain/badge/dto/BadgeEvaluationContext.java, src/main/java/com/moonbaar/domain/badge/dto/BadgeListResponse.java, src/main/java/com/moonbaar/domain/badge/dto/BadgeProgressResponse.java, src/main/java/com/moonbaar/domain/badge/dto/BadgeResponse.java, src/main/java/com/moonbaar/domain/badge/dto/UserBadgeListResponse.java, src/main/java/com/moonbaar/domain/badge/dto/UserBadgeResponse.java, src/main/java/com/moonbaar/domain/badge/entity/Badge.java, src/main/java/com/moonbaar/domain/badge/entity/UserBadge.java, src/main/java/com/moonbaar/domain/badge/enums/BadgeCode.java, src/main/java/com/moonbaar/domain/badge/enums/BadgeType.java, src/main/java/com/moonbaar/domain/badge/exception/BadgeErrorCode.java, src/main/java/com/moonbaar/domain/badge/exception/BadgeNotFoundException.java, src/main/java/com/moonbaar/domain/badge/repository/BadgeRepository.java, src/main/java/com/moonbaar/domain/badge/repository/UserBadgeRepository.java, src/main/java/com/moonbaar/domain/badge/service/BadgeService.java
- #41 
> 소유 배지/다음 목표 조회 및 배지 획득 처리 기능 구현
1. Badge 엔티티와 UserBadge 엔티티를 구현했습니다. 
2. 사용자가 소유한 배지를 조회하는 `GET /users/me/badges` 엔드포인트를 구현했습니다.
3. 사용자가 얻을 수 있는 배지를 찾아 획득 처리하고, 새롭게 획득한 배지를 응답하는 `POST /users/me/badges/new` 엔드포인트를 구현했습니다.
4. 사용자의 다음 목표 배지를 조회하는 `GET /users/me/badges/next` 엔드포인트를 구현했습니다.
배지 획득의 기준이 되는 요소는 `조건`과 `값`입니다.
회의에서 '현재 배지 개수는 27개로 많지 않기 때문에 Java 코드 상에서 검증하자'는 결론을 내렸습니다.
**구현한 구체적인 방법**
1. 자바 코드에서 조건과 값 관리
배지마다 고유한 code를 BadgeCode enum으로 만들어서 `조건`과, `값`을 각각 작성하였습니다.
```Java
public enum BadgeCode {
FIRST_VISIT(stats -> stats.totalVisitCount(), 1),
SEOUL_EXPLORER(stats -> (long) stats.visitedDistrictCount(), 10),
SEOUL_MASTER(stats -> (long) stats.visitedDistrictCount(), 25),
CULTURE_CLASS_EXPLORER(stats -> stats.getVisitCountByCategoryName("교육/체험"), 1),
...
private final …
```
=> feat: 배지 api 구현

src/main/java/com/moonbaar/common/config/CorsProperties.java, src/main/java/com/moonbaar/common/config/SecurityConfig.java, src/main/java/com/moonbaar/common/oauth/handler/OAuth2SuccessHandler.java
~~프론트엔드 배포 서버와 localhost url을 동적으로 redirect url에 설정해주기 위해
request의 origin을 확인하여 redirect url을 생성하도록 했습니다.~~
->
oauth2 인증의 경우 클라이언트의 리퀘스트가 oauth2 provider의 url을 거쳐 백엔드로 오게 됩니다.
이 경우 클라이언트가 보낸 request의 origin, referer가 사라지게 되어
위에서 의도했던 대로 redirect url이 생성되지 않았습니다.
때문에 다시 application.yml에 고정된 값으로 미리 선언하고
해당 url을 사용하도록 했습니다.
허용된 url을 application.yml로 추출했습니다.
리스트로 사용하기 위해 `@Value`가 아닌 `CorsProperties` 컴포넌트를 만들어 사용했습니다.
cors의 setAllowedOrigins을 `CorsProperties`를 사용하도록 했습니다.
=> feat: 프론트엔드 배포 서버 allowed origins 추가

src/main/java/com/moonbaar/domain/event/dto/EventDetailResponse.java, src/main/java/com/moonbaar/domain/event/service/EventService.java, src/main/java/com/moonbaar/domain/like/repository/LikedEventRepository.java, src/main/java/com/moonbaar/domain/visit/repository/VisitRepository.java, src/test/java/com/moonbaar/domain/event/controller/EventControllerTest.java, src/test/java/com/moonbaar/domain/event/service/EventServiceTest.java
- #61 
행사 상세조회 응답에 visitCount, likeCount 필드를 추가했습니다.
자잘한 변경) 기존 응답이 isLiked, isVisited 순으로 작성됐는데 이를 isVisited, isLiked, visitCount, likeCount 순서로 변경했습니다
|항목 | 내용|
|-- | --|
엔드포인트 | /events/{eventId}
메서드 | GET
설명 | 특정 문화행사의 상세 정보 조회
URL 파라미터 | eventId: 행사 ID
인증 | 선택사항 (인증 시 isLiked/isVisited 실제 값으로 포함)
응답 | { "id": "이벤트ID", "title": "행사명", "category": "카테고리", "district": "행정구역", "place": "장소명", "startDate": "2025-04-10T10:00:00Z", "endDate": "2025-04-10T18:00:00Z", "isFree": true, "useFee": "요금 정보", "useTarget": "이용대상", "program": "프로그램 소개", "etcDesc": "상세 설명", "mainImg": "이미지URL", "orgName": "주최자명", "orgLink": "기관 URL", "hmpgAddr": "홈페이지 주소", "latitude": 37.5665, "longitude": 126.9780, "isVisited": false, "isLiked": false, "visitCount": 42, "likeCount": 18 }
오류 코드 | 404: 행사 정보 없음
=> feat: 행사 상세 조회 응답에 방문 횟수, 좋아요 횟수 포함

src/main/java/com/moonbaar/domain/visit/exception/EventNotActiveException.java, src/main/java/com/moonbaar/domain/visit/exception/VisitErrorCode.java, src/main/java/com/moonbaar/domain/visit/service/VisitService.java, src/test/java/com/moonbaar/domain/visit/service/VisitServiceTest.java
방문 인증 시 진행 중인 행사 검증이 누락 되어 있어
진행 기간이 아닌데도 방문 인증을 할 수 있었습니다.
이를 해결하기 위해 방문 인증 시 진행 중인 행사 검증 로직을 추가하였습니다.
=> feat: 방문 인증 시 진행 중인 행사 검증 추가

src/main/java/com/moonbaar/domain/visit/dto/VisitItemResponse.java, src/test/java/com/moonbaar/domain/visit/controller/UserVisitControllerTest.java
api 명세에 따르면 방문 목록 응답에는 방문 ID가 아닌 행사 ID만 있어야 합니다.
현재는 방문 ID를 `id` 필드로 반환하고, 행사 ID는 `eventId`로 따로 반환하고 있어
이를 명세에 맞게 수정했습니다.
=> fix: 방문 목록 응답 필드 수정

src/main/java/com/moonbaar/domain/event/controller/EventController.java, src/main/java/com/moonbaar/domain/event/dto/EventDetailResponse.java, src/main/java/com/moonbaar/domain/event/dto/EventSummaryResponse.java, src/main/java/com/moonbaar/domain/event/dto/EventUserStatusResponse.java, src/main/java/com/moonbaar/domain/event/service/EventService.java, src/test/java/com/moonbaar/domain/event/controller/EventControllerTest.java, src/test/java/com/moonbaar/domain/event/service/EventServiceTest.java
행사 상세 정보와 관련 사용자 정보(좋아요/방문 여부)를 분리된 API로 제공하는 방식으로 변경했습니다.
처음에는 단일 엔드포인트(/events/{eventId})에서 인증 여부에 따라 다른 응답을 제공하려 했으나, 다음과 같은 문제가 있었습니다:
인증 필터 문제: JWT 필터에서 해당 경로를 인증 대상에서 제외하면(shouldNotFilter), 쿠키에 유효한 액세스 토큰이 있어도 인증 정보가 설정되지 않음
인증 강제 문제: 반대로 JWT 필터가 해당 경로를 검사하면, 토큰 없는 요청에 대해 401 오류가 발생하여 비인증 사용자는 기본 정보조차 볼 수 없음
이러한 문제들로 인해 API를 명확히 분리하는 것이 적합하다는 결론에 도달했습니다:
/events/{eventId} - 모든 사용자가 접근 가능한 기본 정보 제공 API
/events/{eventId}/user-status - 인증된 사용자의 상태 정보 제공 API
|항목 | 내용|
|-- | --|
엔드포인트 | /events/{eventId}/users-status
메서드 | GET
설명 | 특정 문화행사의 사용자 관련 정보
URL 파라미터 | eventId: 행사 ID
인증 | 인증 필요
응답 | { "eventId": "이벤트ID", "isVisited": "방문 여부", "isLiked": "좋아요 여부" }
오류 코드 | 404: 행사 정보 없음
=> feat: 사용자별 이벤트 상태 정보 조회 API 구현

src/main/java/com/moonbaar/common/config/SecurityConfig.java, src/main/java/com/moonbaar/domain/event/controller/EventController.java, src/main/java/com/moonbaar/domain/event/dto/EventDetailResponse.java, src/main/java/com/moonbaar/domain/event/dto/EventListResponse.java, src/main/java/com/moonbaar/domain/event/dto/EventSummaryResponse.java, src/main/java/com/moonbaar/domain/event/service/EventService.java, src/main/java/com/moonbaar/domain/visit/repository/VisitRepository.java, src/test/java/com/moonbaar/domain/event/controller/EventControllerTest.java, src/test/java/com/moonbaar/domain/event/service/EventServiceTest.java
- #67
- #26 
- `/events/with-status` 및 `/events/with-status/{eventId}` 엔드포인트를 구현하였습니다.
- 두 엔드포인트 모두 인증이 필요하며, 인증된 유저의 경우 `isVisited`, `isLiked` 값이 실제 사용자 데이터를 기반으로 반환됩니다.
- 행사 리스트 응답에 longitude, latitude 필드를 제거했습니다.
기존 구조를 크게 벗어나지 않게 구현을 했지만 리팩토링이 필요해 보입니다.
`/events/with-status`: 
1. 전체 행사 목록을 조회한 후,
2. 로그인 유저의 방문 행사 ID 리스트를 가져오고,
3. 각 이벤트가 이 리스트에 포함되는지 확인하여 `isVisited` 값을 채웁니다.
현재 로직은 비교적 단순하지만, `contains` 체크가 반복되기 때문에 대규모 데이터에 대해 성능 이슈가 있을 수 있습니다. 추후 개선이 필요해 보입니다.
`/events/with-status/{eventId}`:
- 방문 수, 좋아요 수, 방문 여부, 좋아요 여부를 각각 개별 쿼리로 조회하고 있습니다.
- 추후 단일 쿼리 또는 병렬 쿼리 처리 방식으로 최적화 가능성이 있습니다.
- `/events/with-status`의 `isVisited` 처리 로직을 더 효율적으로 개선할 수 있는 방법 (e.g. Map 기반 처리, SQL 단일 쿼리화, QueryDSL 사용) 을 검토할 예정입니다.
- `/events/with-status/{eventId}`의 통계 정보도 서브쿼리 통합 등을 통해 최적화 여지가 있습니다.
|항목 | 내용| …
=> feat: 유저 정보를 포함하는 행사 목록 조회, 행사 상세 정보 조회 엔드포인트 추가

docker-files/nginx/nginx.conf.template, src/main/java/com/moonbaar/common/config/OAuth2Config.java, src/main/java/com/moonbaar/common/config/SecurityConfig.java, src/main/java/com/moonbaar/common/oauth/CustomAuthorizationRequestRepository.java, src/main/java/com/moonbaar/common/oauth/handler/OAuth2SuccessHandler.java
- #60 
- 인증 request를 기반으로 생성한 redirect uri를 세션에 저장하기 위해 CustomAuthorizationRequestRepository를 구현했습니다.
- OAuth2SuccessHandler에서 세션에 저장된 final_redirect_uri를 사용하도록 수정했습니다.
- nginx 컨테이너에서 "/api"를 제외한 요청은 프론트엔드 서버로 프록시 하도록 설정했습니다.
- allowed origins에 배포 도메인을 추가했습니다.
- Spring Security의 OAuth2는 기본적으로 인증 요청을 HTTP 세션에 저장하고 관리하는데, 이를 확장하여 `final_redirect_uri` attribute를 세션에 저장했습니다.
- 클라이언트의 인증 요청이 백엔드 서버로 오면 referer 헤더에서 도메인을 추출해 redirect uri를 만들어 세션에 저장합니다.
- OAuth 인증 요청은 이미 CORS 검증을 통과한 상태이므로, 별도의 도메인 검증 과정은 생략했습니다.
- 인증 성공 시 OAuth2SuccessHandler에서 세션에 저장된 리다이렉션 URI를 사용하여 사용자를 원래 요청한 클라이언트로 리다이렉션합니다.
- 이전에 `redirect_uri` attribute를 사용했으나 실패했었는데, 해당 attribute가 OAuth2 provider에서 이미 사용 중이었기 때문인 것으로 보입니다. `state`나 `redirect_uri` 파라미터는 기본적으로 oauth2 provider가 사용하는 파라미터입니다. 이를 피해 `final_redirect_uri`로 …
=> feat: oauth2 인증 성공 redirect url 동적으로 생성하기 및 프론트엔드 서버 프록시 설정

src/main/java/com/moonbaar/domain/visit/dto/FootprintResponse.java
- #73 
- 행사의 id가 아니라 방문기록의 id가 돌아가고 있던 문제 해결
=> fix: 발자국 response id 오류 수정
